config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root 'pokemons#index'

  resources :pokemons, only: [:index]
  post 'pokemons/upload', to: 'pokemons#upload'
  post 'pokemons/destroy_all', to: 'pokemons#destroy_all'
  get 'pokemons/clean_up', to: 'pokemons#clean_up'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
require 'csv'

class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def upload
    csv_path = File.join Rails.root, 'db', 'pokemon.csv'
    PokemonAddWorker.perform_async(csv_path)
    flash[:notice] = "Pokemons getting added to db"
    redirect_to pokemons_path
  end

  def destroy_all
    PokemonRemoveWorker.perform_async
    flash[:notice] = "Pokemons getting removed from db"
    redirect_to pokemons_path
  end

  def clean_up
   # GuestsCleanupJob.perform_later("guest")
    GuestsCleanupJob.set(wait: 10.second).perform_later("guest")
    redirect_to pokemons_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemons</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Pokemons</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= link_to "clean up", pokemons_clean_up_path %>

<%= form_tag pokemons_upload_path do %>
  <%= submit_tag "Import Pokemons" %>
<% end %>

<%= form_tag pokemons_destroy_all_path do %>
  <%= submit_tag "Delete Pokemons" %>
<% end %>

<table>
  <tr>
    <th>Index</th>
    <th>Pokemon</th>
    <th>Height</th>
    <th>Weight</th>
  </tr>
  <% @pokemons.each_with_index do |pokemon, index| %>
    <tr>
      <td><%=index%></td>
      <td><%=pokemon.name%></td>
      <td><%=pokemon.height%></td>
      <td><%=pokemon.weight%></td>
    </tr>
  <%end%>
</table>